Repository pytorch/builder, pull requests merged in 2022-12, with the labels that each got.

#1219 Consolidating validation scripts
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-linux-binaries.yml
  .github/workflows/validate-macos-binaries.yml
  .github/workflows/validate-windows-binaries.yml
Labels: cla signed

#1220 Mitigate windows nightly build regressions
  conda/build_pytorch.sh
Labels: cla signed

#1215 Truncate RECORD instead of delete
  manywheel/build_common.sh
  release/pypi/prep_binary_for_pypi.sh
Labels: cla signed

#1221 Add cuda profiler api to cuda install 11.8
  windows/internal/cuda_install.bat
Labels: cla signed

#1224 conda: Add CUDA_HOME, cuda binaries to path
  conda/Dockerfile
  conda/build_docker.sh
Labels: cla signed, binary-docker-images

#1229 Advance build number in pytorch-cuda
  conda/pytorch-cuda/meta.yaml
Labels: cla signed

#1223 Change validaiton script to run smoke tests from vision, audio etc..
  .github/workflows/validate-nightly-binaries.yml
  .github/workflows/validate-windows-binaries.yml
  test/smoke_test/smoke_test.py
Labels: cla signed, with-ssh

#1231 Changes to prep for pypi script for release 1.13.1
  release/pypi/prep_binary_for_pypi.sh
Labels: cla signed

#1230 PyPi binary validation and size check
  .github/workflows/validate-repackaged-binary-sizes.yml
  release/pypi/prep_binary_for_pypi.sh
Labels: cla signed

#1234 Adding new workflow to call from domain libraries to validate on domain libraries such as text
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1235 Add ability to call validate domain library manually
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1236 Adding test for validate domain libary workflow
  .github/workflows/test-validate-domain-library.yml
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1239 Generate Manywheel packages for Intel
  manywheel/Dockerfile_cxx11-abi
Labels: cla signed

#1241 Bump versions for release 1.13.1
  build_aarch64_wheel.py
  release/promote.sh
  release/release_versions.sh
Labels: cla signed

#1242 release: Strip whitespace from version_with_suffix
  release/pypi/prep_binary_for_pypi.sh
Labels: cla signed

#1243 Cuda 11.8 and removal of dev packages
  conda/pytorch-cuda/conda_build_config.yaml
  conda/pytorch-cuda/meta.yaml
Labels: cla signed

#1238 Adding more OS's to validate domain library workflow
  .github/workflows/test-validate-domain-library.yml
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1244 Add target os variable to windows validation
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1245 Update MKL to 2022.1
  common/install_mkl.sh
  wheel/build_wheel.sh
Labels: cla signed

#1196 Adds infra to use nvidia dependencies from pypi and cleans up patches
  common/install_cuda.sh
  manywheel/build_cuda.sh
  release/pypi/prep_binary_for_pypi.sh
Labels: cla signed

#1246 Remove invalid git option
  .circleci/scripts/binary_checkout.sh
  conda/build_pytorch.sh
  cron/nightly_defaults.sh
  wheel/build_wheel.sh
Labels: cla signed

#1247 Revert "Adds infra to use nvidia dependencies from pypi and cleans up…
  common/install_cuda.sh
  manywheel/build_cuda.sh
  release/pypi/prep_binary_for_pypi.sh
Labels: cla signed

#1249 Add with_cuda flag to validate domain library workflow
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1250 Add GPU architecture env variables to validate domain library workflow
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1252 Add cuda to jobname for validate domain library
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1255 Remove pylief dependency
  conda/build_pytorch.sh
Labels: cla signed

#1256 s3_management: Hide specific packages between dates
  s3_management/manage.py
Labels: cla signed

#1257 s3_management: Bump bad dates to october 17th
  s3_management/manage.py
Labels: cla signed

#1258 s3_management: hide torchtriton
  s3_management/manage.py
Labels: cla signed
