Repository pytorch/builder, pull requests merged in 2022-08, with the labels that each got.

#1091 [ROCm] correct libamd_comgr.so.2 path for rocm 5.2
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#1092 Make manywheels workflow depend also on build_rocm.sh
  .github/workflows/build-manywheel-images.yml
Labels: cla signed

#1093 Revert "Make manywheels workflow depend also on build_rocm.sh"
  .github/workflows/build-manywheel-images.yml
Labels: cla signed

#996 release: migrate promote utils from core pytorch
  release/README.md
  release/cut-release-branch.sh
  release/promote.sh
  release/promote/common_utils.sh
  release/promote/conda_to_conda.sh
  release/promote/prep_binary_for_pypi.sh
  release/promote/s3_to_s3.sh
  release/promote/wheel_to_pypi.sh
  release/restore-backup.sh
Labels: cla signed, releng

#1105 release: Make macos platform a variable / glob
  release/pypi/promote_pypi_to_staging.sh
Labels: cla signed

#1079 Add MAGMA patches fixing LU factorization
  .github/workflows/build-magma-linux.yml
  magma/build_magma.sh
  magma/package_files/getrf_nbparam.patch
  magma/package_files/getrf_shfl.patch
  magma/package_files/meta.yaml
Labels: cla signed

#1107 Smoke test binary
  test/smoke_test/smoke_test.py
Labels: cla signed

#1110 Fix for cudatoolkit dependency for 11.7
  conda/build_pytorch.sh
Labels: cla signed

#1114 Change cuda to pytorch-cuda dependency for 11.6 and 11.7
  conda/build_pytorch.sh
Labels: cla signed

#1116 Modify smoke tests for binary validation
  test/smoke_test/smoke_test.py
Labels: cla signed
