Repository pytorch/builder, pull requests merged in 2022-03, with the labels that each got.

#981 Update CUDA release process add checklist
  CUDA_UPGRADE_GUIDE.MD
Labels: cla signed

#983 have cygpath for windows pathing
  conda/build_pytorch.sh
Labels: cla signed

#976 [LTS] Do not install python system-wide for Windows smoke test
  windows/internal/smoke_test.bat
Labels: cla signed

#984 libtorch/build_all_docker.sh: fix typo that TOPDIR is missed
  libtorch/build_all_docker.sh
Labels: cla signed

#985 `manywheel/build_docker.sh`: fix typo
  manywheel/build_docker.sh
Labels: cla signed

#986 Do not rely on conda-forge for building py-3.10 wheels
  wheel/build_wheel.sh
Labels: cla signed

#987 Explicitly turn off USE_CUPTI_SO
  manywheel/build_cuda.sh
Labels: cla signed

#991 Fix M1 conda cross builds
  conda/build_pytorch.sh
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#959 [ROCm] add support for libtorch packages
  .github/workflows/build-libtorch-images.yml
  common/install_rocm.sh
  common/install_rocm_magma.sh
  libtorch/Dockerfile
  libtorch/build_all_docker.sh
  libtorch/build_docker.sh
  manywheel/Dockerfile
  manywheel/build_docker.sh
  manywheel/build_libtorch.sh
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#992 [WIP] ADD 11.6 workflow for docker image build
  .github/workflows/build-conda-images.yml
  common/install_cuda.sh
  conda/Dockerfile
  conda/build_all_docker.sh
Labels: cla signed

#997 Add magma build for CUDA11.6
  .github/workflows/build-magma-linux.yml
  magma/Makefile
Labels: cla signed

#998 Update CUDA_UPGRADE_GUIDE.MD
  CUDA_UPGRADE_GUIDE.MD
Labels: cla signed

#1000 bump cudnn to 8.3.2.44 for CUDA11.3
  common/install_cuda.sh
  conda/pytorch-nightly/build.sh
  manywheel/build_cuda.sh
  windows/internal/cuda_install.bat
Labels: cla signed

#1005 Package cudnn binaries into cuda-11.3
  conda/pytorch-nightly/build.sh
Labels: cla signed

#1003 Build libtorch and manywheel for 11.6
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
  common/install_magma.sh
  libtorch/Dockerfile
  libtorch/build_all_docker.sh
Labels: cla signed, with-ssh

#1008 comment out nvidia repositories
  manywheel/build_common.sh
  manywheel/build_libtorch.sh
  smoke_test.sh
Labels: cla signed

#990 manywheel: add _GLIBCXX_USE_CXX11_ABI=1 support for linux cpu wheel
  manywheel/Dockerfile_cxx11-abi
  manywheel/build.sh
  manywheel/build_all_docker.sh
  manywheel/build_docker.sh
Labels: cla signed
