Repository pytorch/builder, pull requests merged in 2022-01, with the labels that each got.

#913 update conda-build during the install
  conda/build_pytorch.sh
Labels: cla signed

#917 Changes for Py3.10
  conda/build_pytorch.sh
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#919 Revert "Changes for Py3.10"
  conda/build_pytorch.sh
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#916 Rocm4.5.2 manywheel support
  .github/workflows/build-manywheel-images.yml
  common/install_miopen.sh
  common/install_rocm.sh
  common/install_rocm_magma.sh
  manywheel/Dockerfile
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#921 Py3.10 support for binary builds
  conda/build_pytorch.sh
  conda/pytorch-nightly/meta.yaml
  run_tests.sh
Labels: cla signed

#922 Py3.10 support, fix typo in previous commit
  conda/build_pytorch.sh
  conda/pytorch-nightly/meta.yaml
  run_tests.sh
Labels: cla signed

#923 wheel changes for py3.10
  wheel/build_wheel.sh
Labels: cla signed

#924 Py3.10 changes required for MAC builds
  run_tests.sh
Labels: cla signed

#925 Adding py3.10 to windows builds
  windows/condaenv.bat
Labels: cla signed

#926 Pinning cmake version for py3.10 builds
  windows/condaenv.bat
Labels: cla signed

#928 Rocm4.5.2 manywheel support (part 2)
  cron/update_s3_htmls.sh
  manywheel/build_all_docker.sh
Labels: cla signed, module: rocm

#927 Adding py310 to manywheel images
  common/install_cpython.sh
  common/install_openssl.sh
  manywheel/build_common.sh
  manywheel/build_scripts/build.sh
  manywheel/build_scripts/build_utils.sh
Labels: cla signed, with-ssh

#931 Fix py3.10 check binary tests
  check_binary.sh
Labels: cla signed

#933 Revert "Fix py3.10 check binary tests"
  check_binary.sh
Labels: cla signed

#934 Fix py_dot variable initialization
  check_binary.sh
Labels: cla signed

#935 Refactor python_nodot in mac builds
  wheel/build_wheel.sh
Labels: cla signed

#936 windows build fixes for GHA
  windows/internal/cuda_install.bat
  windows/internal/vs2019_install.ps1
Labels: cla signed

#937 windows: Ensure we still set CUDA env vars
  conda/build_pytorch.sh
  windows/internal/cuda_install.bat
Labels: cla signed

#939 [LTS] Pin delocate package to before python 3.6 drop
  wheel/build_wheel.sh
Labels: cla signed

#938 Add libroctracer dependency unconditionally for ROCm
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#940 Smoke test for windows modifications
  windows/internal/smoke_test.bat
Labels: cla signed

#942 Upgrading cudnn for cuda 11.5
  common/install_cuda.sh
  windows/internal/cuda_install.bat
Labels: cla signed

#943 conda: skip tests on windows
  conda/build_pytorch.sh
Labels: cla signed

#944 Revert "Upgrading cudnn for cuda 11.5"
  common/install_cuda.sh
  windows/internal/cuda_install.bat
Labels: cla signed

#945 Upgrading cudnn for cuda 11.5, includes zlib for windows
  common/install_cuda.sh
  windows/internal/cuda_install.bat
Labels: cla signed

#946 windows: Move skip cuda install to above cuda install
  windows/internal/cuda_install.bat
Labels: cla signed

#947 Fix typo when unzipping zlib
  windows/internal/cuda_install.bat
Labels: cla signed

#948 conda: Remove commands from test step
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#949 use PYTORCH_ROOT for pytorch_rootdir
  conda/build_pytorch.sh
  wheel/build_wheel.sh
Labels: cla signed

#950 only use PYTORCH_ROOT if in GHA
  conda/build_pytorch.sh
  wheel/build_wheel.sh
Labels: cla signed
