Repository pytorch/builder, pull requests merged in 2023-01, with the labels that each got.

#1259 s3_management: Add PACKAGE_ALLOW_LIST for indices
  s3_management/manage.py
Labels: cla signed

#1260 s3_management: Bump bad date end to 12/30
  s3_management/manage.py
Labels: cla signed

#1248 Adds infra to use nvidia dependencies from pypi and cleans up patches
  common/install_cuda.sh
  manywheel/build_cuda.sh
  release/pypi/prep_binary_for_pypi.sh
Labels: cla signed

#1261 Fix pytorch-cuda version in nightly
  conda/build_pytorch.sh
Labels: cla signed

#1262 Adding py311 validations for wheel builds
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-linux-binaries.yml
  common/install_cpython.sh
Labels: cla signed

#1265 Use MATRIX variables, simplify logic for validation tests
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-domain-library.yml
  .github/workflows/validate-linux-binaries.yml
  .github/workflows/validate-macos-arm64-binaries.yml
  .github/workflows/validate-macos-binaries.yml
  .github/workflows/validate-nightly-binaries.yml
  .github/workflows/validate-windows-binaries.yml
  check_binary.sh
  test/smoke_test/smoke_test.py
Labels: cla signed

#1266 Fix validation domain library workflow
  .github/workflows/validate-domain-library.yml
Labels: cla signed

#1264 Nightly: do test deps install better and skip CUDA tests on cpu only box
  README.md
  conda/build_pytorch.sh
  run_tests.sh
Labels: cla signed

#1232 Refactor PyTorch wheel and libtorch build scripts for ROCm
  manywheel/build_common.sh
  manywheel/build_libtorch.sh
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#1263 add sm_90 to CUDA11.8 builds
  common/install_conda.sh
  common/install_cuda.sh
  conda/pytorch-nightly/bld.bat
  conda/pytorch-nightly/build.sh
  magma/Makefile
  manywheel/build_cuda.sh
  windows/cuda118.bat
Labels: cla signed

#1275 Revert "add sm_90 to CUDA11.8 builds"
  common/install_conda.sh
  common/install_cuda.sh
  conda/pytorch-nightly/bld.bat
  conda/pytorch-nightly/build.sh
  magma/Makefile
  manywheel/build_cuda.sh
  windows/cuda118.bat
Labels: cla signed

#1268 Set ubuntu distribution correctly for ROCm5.3 and above
  common/install_rocm.sh
Labels: cla signed, module: rocm

#1276 Fix unbound variable error
  common/install_cpython.sh
Labels: cla signed

#1277 Manually invoke bash for miniconda
  common/install_conda.sh
  common/install_cpython.sh
Labels: cla signed

#1278 Add sm_90 to CUDA11.8 builds
  common/install_cuda.sh
  conda/pytorch-nightly/bld.bat
  conda/pytorch-nightly/build.sh
  magma/Makefile
  manywheel/build_cuda.sh
  windows/cuda118.bat
Labels: cla signed

#1270 libtinfo.so version update and logic fix for ROCm libtorch
  manywheel/build_common.sh
  manywheel/build_libtorch.sh
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#1273 Looks like it is not used anywhere.
  conda/debugging_pytorch.sh
  wheel/build_wheel.sh
  windows/build_all.bat
  windows/condaenv.bat
Labels: cla signed

#1284 [BE] Delete `unicode_flags ` build options
  common/install_cpython.sh
Labels: cla signed

#1285 [BE] Define `openssl_flags`
  common/install_cpython.sh
Labels: cla signed

#1283 Build with `--enabled-shared` if `patchelf` is found
  common/install_cpython.sh
  manywheel/Dockerfile
Labels: cla signed

#1271 Update cudnn to 8.7.0.84 for CUDA 11.8 builds
  common/install_cuda.sh
  conda/pytorch-nightly/build.sh
  windows/internal/cuda_install.bat
Labels: cla signed, ciflow/binaries

#1287 [BE] Remove references to Python<3.6
  manywheel/Dockerfile
Labels: cla signed

#1282 Add ability to override cuda archs for conda
  conda/pytorch-nightly/build.sh
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#1288 [ROCm] reduce disk space used in image
  common/install_miopen.sh
  common/install_rocm_magma.sh
Labels: cla signed, module: rocm
