Repository pytorch/builder, pull requests merged in 2023-02, with the labels that each got.

#1290 ci: Migrate to checkout@v3
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-llvm-images.yml
  .github/workflows/build-magma-linux.yml
  .github/workflows/build-magma-windows.yml
  .github/workflows/build-manywheel-images.yml
Labels: cla signed

#1289 Add pypi with cudnn package test
  .github/scripts/validate_binaries.sh
Labels: cla signed

#1225 Upgrade nightly wheels to rocm5.4.2
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
  common/install_miopen.sh
  libtorch/Dockerfile
  libtorch/build_all_docker.sh
  manywheel/Dockerfile
  manywheel/build_all_docker.sh
  manywheel/build_docker.sh
Labels: cla signed, module: rocm

#1295 Add dev packages for windows pytorch-cuda dependencies
  conda/pytorch-cuda/conda_build_config.yaml
  conda/pytorch-cuda/meta.yaml
Labels: cla signed

#1296 rocm libtorch prebuild magma; fix manylinux cmake version
  libtorch/Dockerfile
  libtorch/build_docker.sh
  manywheel/Dockerfile
Labels: cla signed, module: rocm

#1251 Add manywheel:cpu-cxx11-abi checkup for check_binary.sh
  check_binary.sh
Labels: cla signed

#1301 Remove with_py311 flag as. Python 3.11 was added to nightly matrix
  .github/workflows/validate-linux-binaries.yml
Labels: cla signed

#1300 rocm manylinux now uses devtoolset 9
  manywheel/Dockerfile
  manywheel/build_docker.sh
Labels: cla signed, module: rocm

#1291 [aarch64] fix ACL_ROOT_DIR setting and upgrade the ACL version to 22.11
  build_aarch64_wheel.py
Labels: cla signed

#1303 Set torch._C._PYBIND11_BUILD_ABI version check only for GLIBCXX_USE_CXX11_ABI=0
  check_binary.sh
Labels: cla signed

#1297 Adding limit windows builds logic
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-binaries.yml
  .github/workflows/validate-nightly-binaries.yml
  .github/workflows/validate-release-binaries.yml
  .github/workflows/validate-windows-binaries.yml
Labels: cla signed

#1305 Simplify mkl build dependencies
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#1306 Update torch._C._PYBIND11_BUILD_ABI version check
  check_binary.sh
Labels: cla signed

#1310 Put back smoke test label
  windows/internal/smoke_test.bat
Labels: cla signed

#1309 [aarch64] add support for torchdata wheel building
  build_aarch64_wheel.py
Labels: cla signed

#1304 Python 3.11 validation workflow tests
  .github/scripts/validate_binaries.sh
Labels: cla signed, with-ssh

#1312 Add a scheduled workflow for the nightly pypi binary size validation
  .github/workflows/validate-nightly-pypi-wheel-binary-size.yml
Labels: cla signed

#1317 s3: Allow tar.gz as an accepted file extension
  s3_management/manage.py
Labels: cla signed

#1316 Changes for Python 3.11 and smoke Test RC cut
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-release-binaries.yml
Labels: cla signed

#1319 Make sure we don't use GPU runners for any of libtorch validations
  .github/workflows/validate-windows-binaries.yml
Labels: cla signed

#1321 Add `lit` to list of allowed packages
  s3_management/manage.py
Labels: cla signed

#1322 s3: Allow tar.gz as an accepted file extension (#1317)
  s3_management/manage.py
Labels: cla signed

#1324 s3: Add tqdm package req for text
  s3_management/manage.py
Labels: cla signed
