Repository pytorch/builder, pull requests merged in 2023-06, with the labels that each got.

#1412 Fix PyTorch init time due to inefficient libdrm search for amdgpu.ids
  common/install_rocm_drm.sh
Labels: cla signed, module: rocm

#1418 One-step ROCm manywheel/libtorch docker build
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
  common/install_miopen.sh
  common/install_rocm_magma.sh
  libtorch/Dockerfile
  libtorch/build_docker.sh
  manywheel/Dockerfile
  manywheel/build_docker.sh
Labels: cla signed, module: rocm

#1413 Update wheel build scripts for ROCm5.5
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#1420 Add cu12 packages to allow list for download.pytorch.org
  s3_management/manage.py
Labels: cla signed

#1421 Fix ROCm5.4.2 builds breakage
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#1422 Add nvidia-nvjitlink-cu12 to s3 manage
  s3_management/manage.py
Labels: cla signed

#1424 Pin openssl for python 3.9 conda package
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#1425 Pin openssl for py3.8
  conda/pytorch-nightly/meta.yaml
Labels: cla signed

#1426 Add pytorch-triton to small wheel
  manywheel/build_cuda.sh
Labels: cla signed

#1427 [Manywheel] Add Python-3.12.0b2
  common/install_cpython.sh
Labels: cla signed

#1428 Add poetry and pypi tests
  .github/scripts/validate_poetry.sh
  .github/workflows/validate-linux-binaries.yml
  test/smoke_test/smoke_test.py
Labels: cla signed

#1429 smoke test poetry
  .github/scripts/validate_poetry.sh
Labels: cla signed

#1431 Update aarch64 Scripts for CI worflow
  aarch64_linux/aarch64_ci_build.sh
  aarch64_linux/aarch64_wheel_ci_build.py
Labels: cla signed

#1434 Run release validation testing once a day, run nightly a little later in the day
  .github/workflows/validate-nightly-binaries.yml
  .github/workflows/validate-release-binaries.yml
Labels: cla signed

#1408 Remove CUDA 11.7 builds
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-magma-linux.yml
  .github/workflows/build-magma-windows.yml
  .github/workflows/build-manywheel-images.yml
  common/install_cuda.sh
  conda/Dockerfile
  conda/build_all_docker.sh
  conda/build_pytorch.sh
  conda/pytorch-nightly/bld.bat
  conda/pytorch-nightly/build.sh
  libtorch/Dockerfile
  libtorch/build_all_docker.sh
  magma/Makefile
  manywheel/build_all_docker.sh
  manywheel/build_cuda.sh
  windows/cuda117.bat
  windows/internal/build_magma.bat
  windows/internal/cuda_install.bat
  windows/internal/smoke_test.bat
Labels: cla signed

#1435 Add safe directory to all dockerfiles
  conda/Dockerfile
  libtorch/Dockerfile
  manywheel/Dockerfile
Labels: cla signed

#1436 update cuDNN to 8.9.2.26 for CUDA 12.1
  CUDA_UPGRADE_GUIDE.MD
  common/install_cuda.sh
  windows/internal/cuda_install.bat
Labels: cla signed, ciflow/binaries

#1437 update NCCL to 2.18.1
  common/install_cuda.sh
Labels: cla signed, ciflow/binaries

#1441 Fix wheel macos arm64 validations
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-nightly-binaries.yml
  .github/workflows/validate-release-binaries.yml
  test/smoke_test/smoke_test.py
Labels: cla signed
