Repository pytorch/builder, pull requests merged in 2023-12, with the labels that each got.

#1627 [aarch64] ACL, OpenBLAS and mkldnn updates for PyTorch 2.2
  aarch64_linux/aarch64_ci_setup.sh
  aarch64_linux/aarch64_wheel_ci_build.py
  aarch64_linux/build_aarch64_wheel.py
  mkldnn_fix/aarch64-fix-default-build-flags-to-armv8-a.patch
Labels: cla signed

#1632 [RELEASE-ONLY CHANGES] Update triton dep for 2.2 release
  conda/build_pytorch.sh
  manywheel/build_cuda.sh
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#1635 Pin windows intel-openmp to 2023.2.0
  windows/condaenv.bat
Labels: cla signed

#1636 Pin windows intel-openmp to 2023.2.0 (#1635)
  windows/condaenv.bat
Labels: cla signed

#1629 Torch compile test for python 3.8-3.11 linux only
  test/smoke_test/smoke_test.py
Labels: cla signed

#1630 [aarch64] cleanup mkldnn patching
  aarch64_linux/aarch64_wheel_ci_build.py
  aarch64_linux/build_aarch64_wheel.py
  mkldnn_fix/aarch64-fix-readdir-crash.patch
Labels: cla signed

#1637 [BE] Add CI for check_binary.sh changes
  .github/workflows/test-check-binary.yml
  check_binary.sh
Labels: cla signed

#1638 Release 212 testing
  .github/scripts/validate_pipy.sh
  .github/workflows/validate-linux-binaries.yml
Labels: cla signed

#1639 r212
  .github/scripts/validate_pipy.sh
Labels: cla signed

#1640 removevisionaudio
  .github/scripts/validate_pipy.sh
Labels: cla signed

#1641 validation
  .github/workflows/validate-aarch64-linux-binaries.yml
  .github/workflows/validate-linux-binaries.yml
  .github/workflows/validate-macos-arm64-binaries.yml
  .github/workflows/validate-macos-binaries.yml
  .github/workflows/validate-windows-binaries.yml
Labels: cla signed

#1642 Keep nightly 20231010 for ExecuTorch alpha 0.1 for now
  s3_management/manage.py
Labels: cla signed

#1644 [Validations] Validate aarch64 if all is selected
  .github/workflows/validate-binaries.yml
Labels: cla signed

#1645 Fix validation workflow on aarch64 with conda 23.11.0 and GLIBC_2.25
  .github/workflows/validate-aarch64-linux-binaries.yml
  test/smoke_test/smoke_test.py
Labels: cla signed

#1646 Do not hardcode triton version in builder code
  conda/build_pytorch.sh
Labels: cla signed

#1648 aarch64: patch mkl-dnn for xbyak crashes due to /sys not accessible
  aarch64_linux/aarch64_wheel_ci_build.py
  aarch64_linux/build_aarch64_wheel.py
  mkldnn_fix/fix-xbyak-failure.patch
Labels: cla signed

#1647 Update builder images to ROCm6.0
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
  common/install_miopen.sh
  common/install_rocm_magma.sh
  libtorch/build_all_docker.sh
  libtorch/build_docker.sh
  manywheel/build_all_docker.sh
  manywheel/build_docker.sh
Labels: cla signed, module: rocm, ciflow/rocm

#1528 Avoid PRE_CXX11_SYMBOLS false positives
  check_binary.sh
Labels: cla signed

#1650 Add test ops validation for validation workflows
  .github/scripts/validate_test_ops.sh
  .github/workflows/validate-binaries.yml
  .github/workflows/validate-linux-binaries.yml
Labels: cla signed

#1651 Add test ops validation for validation workflows
  .github/scripts/validate_binaries.sh
  .github/workflows/validate-linux-binaries.yml
Labels: cla signed

#1652 Add test ops validation for validation workflows
  .github/scripts/validate_test_ops.sh
Labels: cla signed

#1653 Add test ops validation for validation workflows
  .github/scripts/validate_test_ops.sh
Labels: cla signed

#1654 Add test ops validation for validation workflows
  .github/scripts/validate_test_ops.sh
Labels: cla signed

#1655 Add test ops validation for validation workflows
  .github/scripts/validate_test_ops.sh
Labels: cla signed

#1656 [validations] Add missing required packages
  .github/scripts/validate_test_ops.sh
Labels: cla signed

#1657 [validations] Perform test_ops only on CUDA binaries
  .github/scripts/validate_binaries.sh
  .github/scripts/validate_test_ops.sh
Labels: cla signed

#1658 [validations] Adjust timeout for linux jobs
  .github/workflows/validate-linux-binaries.yml
Labels: cla signed

#1659 [validations] Restrict testing for python 3.8-3.11
  .github/scripts/validate_binaries.sh
  .github/scripts/validate_test_ops.sh
  .github/workflows/validate-linux-binaries.yml
Labels: cla signed

#1660 [validations] Fix use case if INCLUDE_TEST_OPS is not set
  .github/scripts/validate_binaries.sh
Labels: cla signed
