Repository pytorch/builder, pull requests merged in 2023-07, with the labels that each got.

#1444 Prefix path with conda prefix for macos-arm64 runners
  .github/scripts/validate_binaries.sh
Labels: cla signed, with-ssh

#1446 Update build_docker.sh
  manywheel/build_docker.sh
Labels: cla signed

#1449 Fix aarch64 nightly builds
  aarch64_linux/aarch64_ci_build.sh
Labels: cla signed

#1448 Update Docker base images for conda and libtorch
  conda/Dockerfile
  conda/build_docker.sh
  libtorch/Dockerfile
  libtorch/build_docker.sh
Labels: cla signed

#1447 Fix magma installation inside docker container
  common/install_magma.sh
  manywheel/Dockerfile
  manywheel/build_docker.sh
Labels: cla signed

#1445 Do not install llvm:9 into Docker images
  conda/Dockerfile
  libtorch/Dockerfile
  manywheel/Dockerfile
  manywheel/Dockerfile_2014
  manywheel/Dockerfile_cxx11-abi
  manywheel/build_common.sh
  manywheel/build_libtorch.sh
Labels: cla signed

#1451 Rebuild docker images on release builds
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
Labels: cla signed

#1452 Revert "Rebuild docker images on release builds"
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
Labels: cla signed

#1453 Advance libgfortran version for arm64 builds
  aarch64_linux/aarch64_ci_build.sh
Labels: cla signed

#1443 Update builder images to ROCm5.6
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
  common/install_miopen.sh
Labels: cla signed, module: rocm

#1460 [nightly] Pin miniconda install to py310_23.5.2 for macos and windows
  conda/build_pytorch.sh
Labels: cla signed

#1459 Cleanup unused builder files
  cron/nightly_defaults.sh
  manywheel/build_vision.sh
  wheel/build_all.sh
  wheel/build_vision.sh
  wheel/publish_wheels.sh
  wheel/upload.sh
  wheel/upload_wheels_to_pypi.sh
Labels: cla signed

#1461 Cleanup unused builder files
  packaging/windows/build_pypi_pkg_download_proxy/generate_win_pypi_pkg_download_proxy.sh
  packaging/windows/build_pypi_pkg_download_proxy/setup.py
  windows/azure-pipelines.yml
  windows/templates/auth_task.yml
  windows/templates/build_conda.yml
  windows/templates/build_task.yml
  windows/templates/build_wheels.yml
  windows/templates/linux_build_task.yml
  windows/templates/publish_packages.yml
  windows/templates/publish_test_results.yml
  windows/templates/setup_env_for_msagent.yml
  windows/templates/setup_nightly_variables.yml
  windows/templates/upload_to_conda.yml
  windows/templates/upload_to_s3.yml
  windows/templates/vsts_auth.yml
  windows/upload/upload.sh
  windows/upload/win_reorganize.sh
Labels: cla signed

#1442 Add support for ROCm5.6 for nightly wheels
  libtorch/build_all_docker.sh
  manywheel/build_all_docker.sh
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm

#1462 [aarch64][build] Aarch64 lapack fix and ARMCL version update
  aarch64_linux/aarch64_ci_build.sh
  aarch64_linux/aarch64_wheel_ci_build.py
Labels: cla signed

#1464 Remove unused parameter to limit-win-builds from validation workflows
  .github/workflows/validate-binaries.yml
  .github/workflows/validate-nightly-binaries.yml
  .github/workflows/validate-release-binaries.yml
  .github/workflows/validate-windows-binaries.yml
Labels: cla signed

#1466 Run git update-index --chmod=+x on aarch64_ci_build.sh
  aarch64_linux/aarch64_ci_build.sh
Labels: cla signed
