Repository pytorch/builder, pull requests merged in 2024-07, with the labels that each got.

#1899 MKL install use pipy
  common/install_mkl.sh
Labels: cla signed

#1904 Patch mirrorlist.centos.org no longer online
  conda/Dockerfile
  manywheel/Dockerfile
  manywheel/Dockerfile_2014
Labels: cla signed

#1902 [aarch64] Fix for libgfortran.so.5 missing error when running CUDA AR…
  aarch64_linux/aarch64_wheel_ci_build.py
Labels: cla signed

#1906 Add smoke test for CUDA_VISIBLE_DEVICES
  test/smoke_test/smoke_test.py
Labels: cla signed

#1907 Fix libtorch Docker builds
  libtorch/Dockerfile
Labels: cla signed

#1908 Fix MKL install step of Dockerfile_cxx11-abi
  manywheel/Dockerfile_cxx11-abi
Labels: cla signed

#1910 Python 3.13 wheel changes
  wheel/build_wheel.sh
  windows/condaenv.bat
  windows/internal/smoke_test.bat
Labels: cla signed

#1911 Use pypi for mkl-inlcude and mkl-static dependencies
  windows/condaenv.bat
Labels: cla signed

#1893 [ROCm] Use AOTriton as a dynamic library
  common/aotriton_version.txt
  common/install_aotriton.sh
  manywheel/build_rocm.sh
Labels: cla signed, module: rocm, ciflow/rocm

#1909 Fix locale can not change warning
  manywheel/Dockerfile_2_28
Labels: cla signed

#1913 [BE] Remove unused files and dead code
  .circleci/scripts/binary_checkout.sh
  .circleci/scripts/binary_populate_env.sh
  cron/update_s3_htmls.sh
Labels: cla signed

#1890 Typo fix for docker image name
  .circleci/scripts/binary_populate_env.sh
Labels: cla signed

#1915 [validations] Add mkl version print
  test/smoke_test/smoke_test.py
Labels: cla signed

#1912 [Split Build] remove unnessary file removal
  manywheel/build_common.sh
Labels: cla signed

#1916 Add CUDA_VISIBLE_DEVICES check
  .github/scripts/validate_binaries.sh
  test/smoke_test/smoke_test.py
Labels: cla signed

#1917 Update linux manywheel mkl to 2024.2.0
  common/install_mkl.sh
Labels: cla signed

#1918 Don't run cuda check on xpu devices
  check_binary.sh
Labels: cla signed

#1920 [aarch64] set rpath for libs copied for cuda sbsa wheel
  aarch64_linux/aarch64_wheel_ci_build.py
Labels: cla signed

#1926 Docker builds switch back to ephemeral runners
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
Labels: cla signed

#1929 Update torchrec version to v0.8.0
  release/promote.sh
  release/release_versions.sh
Labels: cla signed

#1930 build aarch64 linux cpu wheel with the linker script optimization
  aarch64_linux/aarch64_ci_build.sh
Labels: cla signed

#1931 Validations add call to cuda.init()
  test/smoke_test/smoke_test.py
Labels: cla signed

#1923 Cleanup docker image build workflows and scripts
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
  common/aotriton_version.txt
  common/install_aotriton.sh
  common/install_conda.sh
  common/install_cpython.sh
  common/install_cuda.sh
  common/install_cuda_aarch64.sh
  common/install_jni.sh
  common/install_libpng.sh
  common/install_magma.sh
  common/install_miopen.sh
  common/install_mkl.sh
  common/install_mnist.sh
  common/install_openblas.sh
  common/install_openssl.sh
  common/install_patchelf.sh
  common/install_rocm.sh
  common/install_rocm_drm.sh
  common/install_rocm_magma.sh
  common/install_xpu.sh
  conda/Dockerfile
  conda/README.md
  conda/build_all_docker.sh
  conda/build_docker.sh
  libtorch/Dockerfile
  libtorch/build_docker.sh
  manywheel/Dockerfile
  manywheel/Dockerfile_2014
  manywheel/Dockerfile_2_28
  manywheel/Dockerfile_2_28_aarch64
  manywheel/Dockerfile_aarch64
  manywheel/Dockerfile_cuda_aarch64
  manywheel/Dockerfile_cxx11-abi
  manywheel/Dockerfile_s390x
  manywheel/LICENSE
  manywheel/README.md
  manywheel/build.sh
  manywheel/build_all_docker.sh
  manywheel/build_common.sh
  manywheel/build_cpu.sh
  manywheel/build_cuda.sh
  manywheel/build_docker.sh
  manywheel/build_libtorch.sh
  manywheel/build_rocm.sh
  manywheel/build_scripts/build.sh
  manywheel/build_scripts/build_utils.sh
  manywheel/build_scripts/manylinux1-check.py
  manywheel/build_scripts/ssl-check.py
  manywheel/test_wheel.sh
Labels: cla signed, module: rocm

#1934 Revert "Cleanup docker image build workflows and scripts"
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
  common/aotriton_version.txt
  common/install_aotriton.sh
  common/install_conda.sh
  common/install_cpython.sh
  common/install_cuda.sh
  common/install_cuda_aarch64.sh
  common/install_jni.sh
  common/install_libpng.sh
  common/install_magma.sh
  common/install_miopen.sh
  common/install_mkl.sh
  common/install_mnist.sh
  common/install_openblas.sh
  common/install_openssl.sh
  common/install_patchelf.sh
  common/install_rocm.sh
  common/install_rocm_drm.sh
  common/install_rocm_magma.sh
  common/install_xpu.sh
  conda/Dockerfile
  conda/README.md
  conda/build_all_docker.sh
  conda/build_docker.sh
  libtorch/Dockerfile
  libtorch/build_docker.sh
  manywheel/Dockerfile
  manywheel/Dockerfile_2014
  manywheel/Dockerfile_2_28
  manywheel/Dockerfile_2_28_aarch64
  manywheel/Dockerfile_aarch64
  manywheel/Dockerfile_cuda_aarch64
  manywheel/Dockerfile_cxx11-abi
  manywheel/Dockerfile_s390x
  manywheel/LICENSE
  manywheel/README.md
  manywheel/build.sh
  manywheel/build_all_docker.sh
  manywheel/build_common.sh
  manywheel/build_cpu.sh
  manywheel/build_cuda.sh
  manywheel/build_docker.sh
  manywheel/build_libtorch.sh
  manywheel/build_rocm.sh
  manywheel/build_scripts/build.sh
  manywheel/build_scripts/build_utils.sh
  manywheel/build_scripts/manylinux1-check.py
  manywheel/build_scripts/ssl-check.py
  manywheel/test_wheel.sh
Labels: cla signed

#1933 Update FBGEMM version to v0.8.0
  release/promote.sh
  release/release_versions.sh
Labels: cla signed

#1935 [1/2 Docker builds remove] Remove docker build workflows
  .github/workflows/build-conda-images.yml
  .github/workflows/build-libtorch-images.yml
  .github/workflows/build-manywheel-images.yml
Labels: cla signed

#1936 Windows nightly pin conda-build
  conda/build_pytorch.sh
Labels: cla signed

#1937 [Windows nightly] pin conda version to 23.7.0
  conda/build_pytorch.sh
Labels: cla signed

#1938 [Windows nightly] Use conda=22.9.0 and conda-build=3.26.1
  conda/build_pytorch.sh
Labels: cla signed

#1932 add +PTX to CUDA 12.4 nightly binaries
  manywheel/build_cuda.sh
Labels: cla signed

#1939 [2/2 Docker builds remove] Remove docker build scripts and recipes
  common/aotriton_version.txt
  common/install_aotriton.sh
  common/install_cpython.sh
  common/install_cuda_aarch64.sh
  common/install_jni.sh
  common/install_libpng.sh
  common/install_magma.sh
  common/install_miopen.sh
  common/install_mkl.sh
  common/install_mnist.sh
  common/install_openblas.sh
  common/install_openssl.sh
  common/install_rocm.sh
  common/install_rocm_drm.sh
  common/install_rocm_magma.sh
  common/install_xpu.sh
  conda/Dockerfile
  conda/README.md
  conda/build_all_docker.sh
  conda/build_docker.sh
  libtorch/Dockerfile
  libtorch/build_docker.sh
  manywheel/Dockerfile
  manywheel/Dockerfile_2014
  manywheel/Dockerfile_2_28
  manywheel/Dockerfile_2_28_aarch64
  manywheel/Dockerfile_aarch64
  manywheel/Dockerfile_cuda_aarch64
  manywheel/Dockerfile_cxx11-abi
  manywheel/Dockerfile_s390x
  manywheel/README.md
  manywheel/build_all_docker.sh
  manywheel/build_docker.sh
  manywheel/build_scripts/build.sh
  manywheel/build_scripts/build_utils.sh
  manywheel/build_scripts/manylinux1-check.py
  manywheel/build_scripts/ssl-check.py
Labels: cla signed, module: rocm

#1942 [BE] cleanup install_cuda.sh script
  common/install_cuda.sh
  manywheel/build_cuda.sh
Labels: cla signed

#1941 Use numpy 2.0.0rc1 for windows builds
  windows/condaenv.bat
Labels: cla signed

#1943 Revert "[BE] cleanup install_cuda.sh script"
  common/install_cuda.sh
  manywheel/build_cuda.sh
Labels: cla signed

#1944 Revert "Use numpy 2.0.0rc1 for windows builds"
  windows/condaenv.bat
Labels: cla signed

#1945 Use numpy 2.0.0rc1 for windows builds
  windows/condaenv.bat
Labels: cla signed

#1946 Fix windows nightly failure due to missing setuptools
  windows/condaenv.bat
Labels: cla signed
